import { test, expect } from "@playwright/test";
import { selectAllIn } from "./helpers/editor";

test.describe("Blocks", () => {
  test("heading: add, change text, save, reload shows new text", async ({ page }) => {
    await page.goto("/");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const headingType = page.getByRole("button", { name: "Heading" });
    await expect(headingType).toBeVisible();
    await headingType.click();
    const newHeading = page.getByText("New heading");
    await expect(newHeading).toBeVisible();
    const newHeadingRole = page.getByRole("heading", { name: "New heading" });
    await expect(newHeadingRole).toBeVisible();
    await selectAllIn(newHeadingRole);
    await page.keyboard.type("E2E Heading Block");
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const e2eHeadingBlock = page.getByRole("heading", { name: "E2E Heading Block" }).first();
    await expect(e2eHeadingBlock).toBeVisible();
  });

  test("paragraph: add, type something, save, still there after reload", async ({ page }) => {
    await page.goto("/");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const paragraph = page.getByRole("button", { name: "Paragraph" });
    await expect(paragraph).toBeVisible();
    await paragraph.click();
    const newParagraph = page.getByText("New paragraph...");
    await expect(newParagraph).toBeVisible();
    const p = page.locator("p").filter({ hasText: "New paragraph" });
    await p.click();
    await p.fill("Persisted paragraph from E2E.");
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const persistedParagraphFromE2E = page.getByText("Persisted paragraph from E2E.");
    await expect(persistedParagraphFromE2E).toBeVisible();
  });

  test("banner: add in admin, save, appears on home", async ({ page }) => {
    await page.goto("/admin");
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const banner = page.getByRole("button", { name: "Banner" });
    await expect(banner).toBeVisible();
    await banner.click();
    const bannerTitle = page.getByText("Banner title");
    await expect(bannerTitle).toBeVisible();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.goto("/");
    const bannerTitle2 = page.getByText("Banner title");
    await expect(bannerTitle2).toBeVisible();
  });

  test("list: add, save, items still there after reload", async ({ page }) => {
    await page.goto("/admin");
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const list = page.getByRole("button", { name: "List" });
    await expect(list).toBeVisible();
    await list.click();
    const firstItem = page.getByText("First item");
    await expect(firstItem).toBeVisible();
    const secondItem = page.getByText("Second item");
    await expect(secondItem).toBeVisible();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const firstItem2 = page.getByText("First item");
    await expect(firstItem2).toBeVisible();
  });

  test("table: add, save, headers/cells on frontend", async ({ page }) => {
    await page.goto("/admin");
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const table = page.getByRole("button", { name: "Table" });
    await expect(table).toBeVisible();
    await table.click();
    const header1 = page.getByText("Header 1");
    await expect(header1).toBeVisible();
    const cell1 = page.getByText("Cell 1");
    await expect(cell1).toBeVisible();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.goto("/");
    const header12 = page.getByText("Header 1");
    await expect(header12).toBeVisible();
  });

  test("image: add and save — block appears", async ({ page }) => {
    await page.goto("/admin");
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const image = page.getByRole("button", { name: "Image" });
    await expect(image).toBeVisible();
    await image.click();
    const imageURL = page.getByPlaceholder("Image URL");
    await expect(imageURL).toBeVisible();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
  });

  test("showcase: add and save", async ({ page }) => {
    await page.goto("/admin");
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const showcase = page.getByRole("button", { name: "Showcase" });
    await expect(showcase).toBeVisible();
    await showcase.click();
    const featureTitle = page.getByText("Feature title");
    await expect(featureTitle).toBeVisible();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
  });

  test("add paragraph then remove it, save — gone after reload", async ({ page }) => {
    await page.goto("/");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const paragraph = page.getByRole("button", { name: "Paragraph" });
    await expect(paragraph).toBeVisible();
    await paragraph.click();
    const newParagraph = page.getByText("New paragraph...");
    await expect(newParagraph).toBeVisible();
    const removeBtn = page.getByTitle("Remove block").last();
    await removeBtn.click();
    const newParagraph2 = page.getByText("New paragraph...");
    await expect(newParagraph2).not.toBeVisible();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const newParagraph3 = page.getByText("New paragraph...");
    await expect(newParagraph3).not.toBeVisible();
  });

  test("move block down, save — order kept after reload", async ({ page }) => {
    await page.goto("/");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const heading = page.getByRole("button", { name: "Heading" });
    await expect(heading).toBeVisible();
    await heading.click();
    const newHeading = page.getByText("New heading");
    await expect(newHeading).toBeVisible();
    const moveDown = page.getByTitle("Move down").first();
    await moveDown.click();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const headings = page.getByRole("heading");
    const count = await headings.count();
    expect(count).toBeGreaterThanOrEqual(2);
  });

  test("two-col: add block in left column, save, visible on reload", async ({ page }) => {
    await page.goto("/");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const twoColumns = page.getByRole("button", { name: "Two columns" });
    await expect(twoColumns).toBeVisible();
    await twoColumns.click();
    const addBlockLeft = page.getByRole("button", { name: /Add block \(left\)/i });
    await expect(addBlockLeft).toBeVisible();
    await addBlockLeft.click();
    const paragraph = page.getByRole("button", { name: "Paragraph" });
    await expect(paragraph).toBeVisible();
    await paragraph.click();
    const newParagraph = page.getByText("New paragraph...");
    await expect(newParagraph).toBeVisible();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const newParagraph2 = page.getByText("New paragraph...");
    await expect(newParagraph2).toBeVisible();
  });

  test("edit about page title, save — new title on reload", async ({ page }) => {
    await page.goto("/about");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const aboutH1 = page.getByRole("heading", { level: 1 });
    await expect(aboutH1).toBeVisible();
    await aboutH1.click({ clickCount: 3 });
    await page.keyboard.type(" About Updated");
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const pageH1 = page.getByRole("heading", { level: 1 });
    await expect(pageH1).toContainText("About Updated");
  });

  test("add two paragraphs, save — both on reload", async ({ page }) => {
    await page.goto("/");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const paragraph = page.getByRole("button", { name: "Paragraph" });
    await expect(paragraph).toBeVisible();
    await paragraph.click();
    const newParagraph = page.getByText("New paragraph...");
    await expect(newParagraph).toBeVisible();
    const addBlockMain2 = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain2).toBeVisible();
    await addBlockMain2.click();
    const paragraph2 = page.getByRole("button", { name: "Paragraph" });
    await expect(paragraph2).toBeVisible();
    await paragraph2.click();
    const paras = page.locator("p").filter({ hasText: "New paragraph" });
    await expect(paras).toHaveCount(2);
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const newParagraph2 = page.locator("p").filter({ hasText: "New paragraph" });
    await expect(newParagraph2).toHaveCount(2);
  });

  test("move block up, save — order kept", async ({ page }) => {
    await page.goto("/");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const heading = page.getByRole("button", { name: "Heading" });
    await expect(heading).toBeVisible();
    await heading.click();
    const newHeading = page.getByText("New heading");
    await expect(newHeading).toBeVisible();
    const moveUp = page.getByTitle("Move up").last();
    await moveUp.click();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const newHeading2 = page.getByText("New heading");
    await expect(newHeading2).toBeVisible();
  });

  test("three-col: add block in right column, save, visible on reload", async ({ page }) => {
    await page.goto("/");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const threeColumns = page.getByRole("button", { name: "Three columns" });
    await expect(threeColumns).toBeVisible();
    await threeColumns.click();
    const addBlockRight = page.getByRole("button", { name: /Add block \(right\)/i });
    await expect(addBlockRight).toBeVisible();
    await addBlockRight.click();
    const paragraph = page.getByRole("button", { name: "Paragraph" });
    await expect(paragraph).toBeVisible();
    await paragraph.click();
    const newParagraph = page.getByText("New paragraph...");
    await expect(newParagraph).toBeVisible();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const newParagraph2 = page.getByText("New paragraph...");
    await expect(newParagraph2).toBeVisible();
  });

  test("remove block from left column when two-col", async ({ page }) => {
    await page.goto("/");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const twoColumns = page.getByRole("button", { name: "Two columns" });
    await expect(twoColumns).toBeVisible();
    await twoColumns.click();
    const addBlockLeft = page.getByRole("button", { name: /Add block \(left\)/i });
    await expect(addBlockLeft).toBeVisible();
    await addBlockLeft.click();
    const paragraph = page.getByRole("button", { name: "Paragraph" });
    await expect(paragraph).toBeVisible();
    await paragraph.click();
    const newParagraph = page.getByText("New paragraph...");
    await expect(newParagraph).toBeVisible();
    const removeInLeft = page.locator(".layout-sidebar-left").getByTitle("Remove block");
    await removeInLeft.click();
    const newParagraph2 = page.getByText("New paragraph...");
    await expect(newParagraph2).not.toBeVisible();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const newParagraph3 = page.getByText("New paragraph...");
    await expect(newParagraph3).not.toBeVisible();
  });

  test("edit banner title, save — new title on frontend", async ({ page }) => {
    await page.goto("/admin");
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const banner = page.getByRole("button", { name: "Banner" });
    await expect(banner).toBeVisible();
    await banner.click();
    const bannerTitle = page.getByText("Banner title");
    await expect(bannerTitle).toBeVisible();
    await bannerTitle.click({ clickCount: 3 });
    await page.keyboard.type(" Custom Banner");
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.goto("/");
    const bannerTitle2 = page.getByText("Banner title Custom Banner");
    await expect(bannerTitle2).toBeVisible();
  });

  test("edit list item, save — text on frontend", async ({ page }) => {
    await page.goto("/admin");
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const list = page.getByRole("button", { name: "List" });
    await expect(list).toBeVisible();
    await list.click();
    const firstItem = page.getByText("First item");
    await expect(firstItem).toBeVisible();
    const first = page.getByText("First item");
    await first.click({ clickCount: 3 });
    await page.keyboard.type(" E2E edited");
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const firstItemE2EEdited = page.getByText("First item E2E edited");
    await expect(firstItemE2EEdited).toBeVisible();
  });

  test("edit showcase title, save", async ({ page }) => {
    await page.goto("/admin");
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const showcase = page.getByRole("button", { name: "Showcase" });
    await expect(showcase).toBeVisible();
    await showcase.click();
    const featureTitle = page.getByText("Feature title");
    await expect(featureTitle).toBeVisible();
    const title = page.getByText("Feature title");
    await title.click({ clickCount: 3 });
    await page.keyboard.type(" Edited");
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const featureTitleEdited = page.getByText("Feature title Edited");
    await expect(featureTitleEdited).toBeVisible();
  });

  test("add heading on blog page, save, visible on reload", async ({ page }) => {
    await page.goto("/blog");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const heading = page.getByRole("button", { name: "Heading" });
    await expect(heading).toBeVisible();
    await heading.click();
    const newHeading = page.getByText("New heading");
    await expect(newHeading).toBeVisible();
    const h = page.getByRole("heading", { name: "New heading" });
    await h.click({ clickCount: 3 });
    await page.keyboard.type(" Blog E2E");
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const newHeading2 = page.getByText("New heading Blog E2E");
    await expect(newHeading2).toBeVisible();
  });

  test("add paragraph on contact page, save", async ({ page }) => {
    await page.goto("/contact");
    const editButton = page.getByRole("button", { name: /Edit this page/i });
    await expect(editButton).toBeVisible();
    await editButton.click();
    const addBlockMain = page.getByRole("button", { name: /Add block \(main\)/i });
    await expect(addBlockMain).toBeVisible();
    await addBlockMain.click();
    const paragraph = page.getByRole("button", { name: "Paragraph" });
    await expect(paragraph).toBeVisible();
    await paragraph.click();
    const newParagraph = page.getByText("New paragraph...");
    await expect(newParagraph).toBeVisible();
    const saveButton = page.getByRole("button", { name: /Save/i });
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    const savedStatus = page.getByRole("status");
    await expect(savedStatus).toHaveText(/Saved!/i);
    await page.reload();
    const newParagraph2 = page.getByText("New paragraph...");
    await expect(newParagraph2).toBeVisible();
  });
});
