-- AlterTable
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "mainComponent" TEXT DEFAULT 'content';
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "leftComponent" TEXT DEFAULT 'content';
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "rightComponent" TEXT DEFAULT 'content';
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "modules" TEXT;
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'published';
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "seo" TEXT;
